// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../myproject-deps/myProjectBar.js', ['myproject.bar'], ['goog.string'], false);
goog.addDependency('../../../myproject-deps/myProjectFoo.js', ['myproject.foo'], ['goog.array', 'goog.dom', 'myproject.bar'], false);
